version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@testing-library/user-event"
    versions:
    - 13.0.0
    - 13.0.1
    - 13.0.10
    - 13.0.11
    - 13.0.12
    - 13.0.13
    - 13.0.14
    - 13.0.15
    - 13.0.16
    - 13.0.2
    - 13.0.3
    - 13.0.4
    - 13.0.5
    - 13.0.6
    - 13.0.7
    - 13.0.8
    - 13.0.9
    - 13.1.0
    - 13.1.1
    - 13.1.2
    - 13.1.3
    - 13.1.5
    - 13.1.6
    - 13.1.7
  - dependency-name: "@types/node"
    versions:
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.11.10
    - 5.11.9
  - dependency-name: immer
    versions:
    - 8.0.2
    - 8.0.3
    - 8.0.4
    - 9.0.0
    - 9.0.1
  - dependency-name: react-dom
    versions:
    - 17.0.1
  - dependency-name: "@types/react"
    versions:
    - 17.0.3
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.5
  - dependency-name: typescript
    versions:
    - 4.2.3
  - dependency-name: node-notifier
    versions:
    - 8.0.1
  - dependency-name: object-path
    versions:
    - 0.11.5
  - dependency-name: elliptic
    versions:
    - 6.5.4
